# Generated by Django 3.1.7 on 2021-03-30 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.hoyrx')),
            ],
        ),
    ]
